# Generated by Django 4.1.2 on 2022-11-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.URLField(
                blank=True,
                default="https://www.mericity.com/resources/images/Default.jpg",
                max_length=300,
            ),
        ),
    ]
