# Generated by Django 4.1.2 on 2022-11-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.webp", upload_to="profile_pics"),
        ),
    ]
