# Generated by Django 4.1.2 on 2022-10-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_post_blog_view_remove_post_updated_date_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_image",
            field=models.URLField(
                blank=True,
                default="https://www.mericity.com/resources/images/Default.jpg",
                max_length=300,
            ),
        ),
    ]
